# local_backend: true

backend:
  name: git-gateway
  branch: main

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
- name: "fishes"
  label: "Fishes"
  label_singular: "Fish"
  folder: "src/content/fishes"
  create: true
  slug: "{{name}}_{{year}}-{{month}}-{{day}}"
  fields:
    - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/fish-profile.njk" }
    - { label: "Name", name: "name", widget: "string" }
    - { label: "Aquarium", name: "aquarium", widget: "select",
      options: [
        "1.1", "1.2", "1.3", "1.4", "1.5", "1.6",
        "2.1", "2.2", "2.3", "2.4", "2.5", "2.6"
      ] }
    - { label: "Image", name: "image", widget: "image" }
    - { label: "Description", name: "body", widget: "markdown" }
