# local_backend: true

backend:
    name: git-gateway
    branch: main

media_folder: "src/assets/images/uploads"
public_folder: "/assets/images/uploads"
logo_url: "/assets/icons/favicon.svg"

collections:
  - label: "Fishes"
    label_singular: "Fish"
    name: "fishes"
    folder: "src/content/fishes"
    create: true
    slug: "{{latin}}_{{day}}-{{month}}-{{year}}_{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "layouts/fish-profile.njk" }
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Latin", name: "latin", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Aquarium", name: "aquarium", widget: "relation", multiple: true, collection: "aquariums", search_fields: ["name"], value_field: "name" }
      - { label: "Sold out", name: "soldout", widget: "boolean", default: false }
      - { label: "Notes", name: "body", widget: "markdown" }
    sortable_fields: ["name"]
    view_groups:
      - label: "Latin"
        field: "latin"
      - label: "Aquarium"
        field: "aquarium"
  - label: "Aquariums"
    label_singular: "Aquarium"
    name: "aquariums"
    folder: "src/content/aquariums"
    create: true
    slug: "{{name}}_{{day}}-{{month}}-{{year}}_{{hour}}-{{minute}}-{{second}}"
    fields:
      - { label: "Name", name: "name", widget: "string" }
    sortable_fields: ["name"]
